### ISSUE TITLE
Erreur lors du lancement d'un test

### ISSUE THREAD

**Issue by bachrc** [ULH-WebDevelopment/ObjectModelLab#2]
Dans mon fork, j'ai uniquement modifié les deux fichiers de source et de test. Cependant, lorsque je veux exécuter mon test à l'aide d'un `npm test` , il me sort ceci : 
```
> object-model-lab@1.0.0 test /home/totorolepacha/Dropbox/Notes/IDOD/ObjectModelLab
> cross-env NODE_ENV=test mocha --recursive --compilers js:babel-register --require ./test/setup.js --watch

module.js:471
    throw err;
    ^

Error: Cannot find module '../dist'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/totorolepacha/Dropbox/Notes/IDOD/ObjectModelLab/node_modules/.bin/cross-env:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! Test failed.  See above for more details.
 ✘ bachrc@Mettaton  ~/Dropbox/Notes/IDOD/ObjectModelLab   master ●  npm -v
3.10.9
 bachrc@Mettaton  ~/Dropbox/Notes/IDOD/ObjectModelLab   master ●  node -v
v6.9.1
```

Et à but d'information, mon `npm install` me donne ceci : 

```
 ✘ totorolepacha@Mettaton  ~/Dropbox/Notes/IDOD/ObjectModelLab   master ●  npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN object-model-lab@1.0.0 No repository field.
```

J'ai bien sûr recherché, mais rien n'a su corriger mon problème. J'ai cru voir que c'était un conflit avec les paquets globaux, mais mon installation de node est pourtant toute fraiche.

Je suis sous Debian Jessie.

**Comment by remnil** [comment]
Les warnings à l'installation ne sont pas un problème, ne me demande pas ce qu'ils sont mais je les ait toujours alors que tout marche.

Je viens de regarder tes classes et je vois surtout qu'il n'y a rien dans ta classe de test

**Comment by bachrc** [comment]
@remnil C'était le template par défaut de la classe de test, elle n'est pas censée renvoyer d'erreur, et pourtant.
J'ai commit et push mon fichier de test "rempli".

**Comment by bachrc** [comment]
Après une suppression du dossier "node_modules" et un `npm install`, le problème est parti. C'est étrange mais bon. Je ferme l'issue.
